In [2]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.10.1-cp312-cp312-win_amd64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Downloading pymongo-4.10.1-cp312-cp312-win_amd64.whl (926 kB)
   ---------------------------------------- 0.0/926.7 kB ? eta -:--:--
   --------------------------------------- 926.7/926.7 kB 21.4 MB/s eta 0:00:00
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.7.0 pymongo-4.10.1

In [4]:
from pymongo import MongoClient

In [9]:
import pandas as pd

In [6]:
client = MongoClient('mongodb+srv://kaorat:kaorat@cluster0.6bukw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0')

In [99]:
research_col = client['db1']['visual_trend_data']

In [100]:
df = pd.read_csv("merged_trend_data.csv")

In [101]:
df

                                   Keyword  Year  Count
0                         Machine Learning  2018     25
1                         Machine Learning  2019     60
2                         Machine Learning  2020     90
3                         Machine Learning  2021    185
4                         Machine Learning  2022    197
5                         Machine Learning  2023    286
6                           Climate Change  2018      5
7                           Climate Change  2019     20
8                           Climate Change  2020     28
9                           Climate Change  2021     69
10                          Climate Change  2022     72
11                          Climate Change  2023    100
12                                COVID-19  2018      0
13                                COVID-19  2019      0
14                                COVID-19  2020     29
15                                COVID-19  2021     80
16                                COVID-19  2022    108
17                                COVID-19  2023     70
18  Hadron-Hadron scattering (experiments)  2018     58
19  Hadron-Hadron scattering (experiments)  2019     35
20  Hadron-Hadron scattering (experiments)  2020     31
21  Hadron-Hadron scattering (experiments)  2021     28
22  Hadron-Hadron scattering (experiments)  2022      0
23  Hadron-Hadron scattering (experiments)  2023      0
24                            Inflammation  2018     21
25                            Inflammation  2019     26
26                            Inflammation  2020     24
27                            Inflammation  2021     32
28                            Inflammation  2022     15
29                            Inflammation  2023     12
30                                     HIV  2018     20
31                                     HIV  2019     21
32                                     HIV  2020     20
33                                     HIV  2021     17
34                                     HIV  2022     19
35                                     HIV  2023     17

In [102]:
dic_lit = df.to_dict(orient='records')

In [103]:
len(dic_lit)

36

In [104]:
research_col.insert_many(dic_lit)

InsertManyResult([ObjectId('67554adbeb5d0df312c93021'), ObjectId('67554adbeb5d0df312c93022'), ObjectId('67554adbeb5d0df312c93023'), ObjectId('67554adbeb5d0df312c93024'), ObjectId('67554adbeb5d0df312c93025'), ObjectId('67554adbeb5d0df312c93026'), ObjectId('67554adbeb5d0df312c93027'), ObjectId('67554adbeb5d0df312c93028'), ObjectId('67554adbeb5d0df312c93029'), ObjectId('67554adbeb5d0df312c9302a'), ObjectId('67554adbeb5d0df312c9302b'), ObjectId('67554adbeb5d0df312c9302c'), ObjectId('67554adbeb5d0df312c9302d'), ObjectId('67554adbeb5d0df312c9302e'), ObjectId('67554adbeb5d0df312c9302f'), ObjectId('67554adbeb5d0df312c93030'), ObjectId('67554adbeb5d0df312c93031'), ObjectId('67554adbeb5d0df312c93032'), ObjectId('67554adbeb5d0df312c93033'), ObjectId('67554adbeb5d0df312c93034'), ObjectId('67554adbeb5d0df312c93035'), ObjectId('67554adbeb5d0df312c93036'), ObjectId('67554adbeb5d0df312c93037'), ObjectId('67554adbeb5d0df312c93038'), ObjectId('67554adbeb5d0df312c93039'), ObjectId('67554adbeb5d0df312c9303a'), ObjectId('67554adbeb5d0df312c9303b'), ObjectId('67554adbeb5d0df312c9303c'), ObjectId('67554adbeb5d0df312c9303d'), ObjectId('67554adbeb5d0df312c9303e'), ObjectId('67554adbeb5d0df312c9303f'), ObjectId('67554adbeb5d0df312c93040'), ObjectId('67554adbeb5d0df312c93041'), ObjectId('67554adbeb5d0df312c93042'), ObjectId('67554adbeb5d0df312c93043'), ObjectId('67554adbeb5d0df312c93044')], acknowledged=True)

In [95]:
data = research_col.find({})

In [97]:
data = list(data)

In [98]:
len(data)

66

In [75]:
df_1 = pd.DataFrame(data)

In [77]:
df_1

,_id,Title,ref_count,Author_count,Subject_area_count,Unique_affiliations_count,Open_access,subtype,Cite_count
0,67553ddfeb5d0df312c8caf8,Public health and international epidemiology f...,76.0,2,1,6,0.0,ch,1.0
1,67553ddfeb5d0df312c8caf9,Flexible Printed Active Antenna for Digital Te...,4.0,2,2,1,0.0,cp,1.0
2,67553ddfeb5d0df312c8cafa,Parametric study of hydrogen production via so...,42.0,4,3,1,0.0,ar,21.0
3,67553ddfeb5d0df312c8cafb,Superhydrophobic coating from fluoroalkylsilan...,45.0,8,5,6,0.0,ar,37.0
4,67553ddfeb5d0df312c8cafc,Electrochemical impedance-based DNA sensor usi...,55.0,6,4,4,0.0,ar,68.0
...,...,...,...,...,...,...,...,...,...
20211,675545cdeb5d0df312c919eb,Long-chain bio-olefins production via oxidativ...,63.0,5,2,2,0.0,ar,3.0
20212,675545cdeb5d0df312c919ec,Recent Developments and Applications of Microf...,115.0,3,1,1,0.0,re,11.0
20213,675545cdeb5d0df312c919ed,"Social justice, education and peacebuilding: c...",76.0,1,1,2,1.0,ar,5.0
20214,675545cdeb5d0df312c919ee,Effects of black soldier fly (Hermetia illucen...,44.0,4,2,2,0.0,ar,6.0
20215,675545cdeb5d0df312c919ef,Effects of remittances on household poverty an...,58.0,1,3,2,0.0,ar,3.0