In [19]:
import pandas as pd
import os

In [20]:
script_dir = os.getcwd()
file_path_2018 = os.path.join(script_dir, '2018_trend_topic.csv')
file_path_2019 = os.path.join(script_dir, '2019_trend_topic.csv')
file_path_2020 = os.path.join(script_dir, '2020_trend_topic.csv')
file_path_2021 = os.path.join(script_dir, '2021_trend_topic.csv')
file_path_2022 = os.path.join(script_dir, '2022_trend_topic.csv')
file_path_2023 = os.path.join(script_dir, '2023_trend_topic.csv')
data_2018 = pd.read_csv(file_path_2018)
data_2019 = pd.read_csv(file_path_2019)
data_2020 = pd.read_csv(file_path_2020)
data_2021 = pd.read_csv(file_path_2021)
data_2022 = pd.read_csv(file_path_2022)
data_2023 = pd.read_csv(file_path_2023)

data_2018['Year'] = 2018
data_2019['Year'] = 2019
data_2020['Year'] = 2020
data_2021['Year'] = 2021
data_2022['Year'] = 2022
data_2023['Year'] = 2023

In [21]:
# Merge 2018 and 2019

data_merged = pd.concat([data_2018, data_2019], axis=0)

# Merge merged and 2020

data_merged = pd.concat([data_merged, data_2020], axis=0)

# Merge merged and 2021

data_merged = pd.concat([data_merged, data_2021], axis=0)

# Merge merged and 2022

data_merged = pd.concat([data_merged, data_2022], axis=0)

# Merge merged and 2023

data_merged = pd.concat([data_merged, data_2023], axis=0)

data_merged['subject_area'] = data_merged['subject_area'].str.split(', ')
data_merged = data_merged.explode('subject_area').reset_index(drop=True)

data_2018['subject_area'] = data_2018['subject_area'].str.split(', ')
data_2018 = data_2018.explode('subject_area').reset_index(drop=True)

data_2019['subject_area'] = data_2019['subject_area'].str.split(', ')
data_2019 = data_2019.explode('subject_area').reset_index(drop=True)

data_2020['subject_area'] = data_2020['subject_area'].str.split(', ')
data_2020 = data_2020.explode('subject_area').reset_index(drop=True)

data_2021['subject_area'] = data_2018['subject_area'].str.split(', ')
data_2021 = data_2021.explode('subject_area').reset_index(drop=True)

data_2022['subject_area'] = data_2018['subject_area'].str.split(', ')
data_2022 = data_2022.explode('subject_area').reset_index(drop=True)

data_2023['subject_area'] = data_2018['subject_area'].str.split(', ')
data_2023 = data_2023.explode('subject_area').reset_index(drop=True)

data_merged

,Title,cover_date,subject_area,Year
0,Public health and international epidemiology f...,2018-12-31,MEDI,2018
1,Flexible Printed Active Antenna for Digital Te...,2018-12-31,ENGI,2018
2,Flexible Printed Active Antenna for Digital Te...,2018-12-31,MATE,2018
3,Parametric study of hydrogen production via so...,2018-12-31,CHEM,2018
4,Parametric study of hydrogen production via so...,2018-12-31,CENG,2018
...,...,...,...,...
50059,Effects of black soldier fly (Hermetia illucen...,2023-01-01,ENVI,2023
50060,Effects of black soldier fly (Hermetia illucen...,2023-01-01,AGRI,2023
50061,Effects of remittances on household poverty an...,2023-01-01,SOCI,2023
50062,Effects of remittances on household poverty an...,2023-01-01,SOCI,2023
50063,Effects of remittances on household poverty an...,2023-01-01,SOCI,2023

In [22]:
key_count_merged = data_merged['subject_area'].value_counts().reset_index().sort_values(by=['count'], ascending=False)
key_count_merged.head(15)

   subject_area  count
0          MEDI   8109
1          ENGI   4172
2          COMP   3985
3          BIOC   3398
4          CHEM   3122
5          MATE   2952
6          ENVI   2882
7          AGRI   2518
8          PHYS   2313
9          SOCI   2047
10         ENER   1845
11         CENG   1842
12         PHAR   1545
13         IMMU   1369
14         MULT   1088

In [23]:
MEDI_list = []
ENGI_list = []
COMP_list = []
BIOC_list = []
CHEM_list = []
MATE_list = []
ENVI_list = []
AGRI_list = []
PHYS_list = []
SOCI_list = []
ENER_list = []
all_code_list = ['MEDI', 'ENGI', 'COMP', 'BIOC', 'CHEM', 'MATE', 'ENVI', 'AGRI', 'PHYS', 'SOCI', 'ENER']
all_list = []
for code in all_code_list:
  result = []
  result.clear()
  for i in range(2018, 2024):
    key_count = data_merged[(data_merged['Year'] == i)]['subject_area'].value_counts().reset_index().sort_values(by=['count'], ascending=False)
    result.append(key_count['count'][key_count['subject_area'] == code].sum())
  all_list.append(result)
# for  in range(2018,2024):
#   key_count = data_merged[(data_merged['Year'] == i)]['subject_area'].value_counts().reset_index().sort_values(by=['count'], ascending=False)
#   result = []
#   result.clear()
#   for code in all_code_list:
#     result.append(key_count['count'][key_count['subject_area'] == code].sum())
#   all_list.append(result)

MEDI_list = all_list[0]
ENGI_list = all_list[1]
COMP_list = all_list[2]
BIOC_list = all_list[3]
CHEM_list = all_list[4]
MATE_list = all_list[5]
ENVI_list = all_list[6]
AGRI_list = all_list[7]
PHYS_list = all_list[8]
SOCI_list = all_list[9]
ENER_list = all_list[10]

In [24]:
ENER_list

[157, 275, 329, 362, 454, 268]

In [25]:
data = [
  ['MEDI', 2018, MEDI_list[0]],
  ['MEDI', 2019, MEDI_list[1]],
  ['MEDI', 2020, MEDI_list[2]],
  ['MEDI', 2021, MEDI_list[3]],
  ['MEDI', 2022, MEDI_list[4]],
  ['MEDI', 2023, MEDI_list[5]],
  ['ENGI', 2018, ENGI_list[0]],
  ['ENGI', 2019, ENGI_list[1]],
  ['ENGI', 2020, ENGI_list[2]],
  ['ENGI', 2021, ENGI_list[3]],
  ['ENGI', 2022, ENGI_list[4]],
  ['ENGI', 2023, ENGI_list[5]],
  ['COMP', 2018, COMP_list[0]],
  ['COMP', 2019, COMP_list[1]],
  ['COMP', 2020, COMP_list[2]],
  ['COMP', 2021, COMP_list[3]],
  ['COMP', 2022, COMP_list[4]],
  ['COMP', 2023, COMP_list[5]],
  ['BIOC', 2018, BIOC_list[0]],
  ['BIOC', 2019, BIOC_list[1]],
  ['BIOC', 2020, BIOC_list[2]],
  ['BIOC', 2021, BIOC_list[3]],
  ['BIOC', 2022, BIOC_list[4]],
  ['BIOC', 2023, BIOC_list[5]],
  ['CHEM', 2018, CHEM_list[0]],
  ['CHEM', 2019, CHEM_list[1]],
  ['CHEM', 2020, CHEM_list[2]],
  ['CHEM', 2021, CHEM_list[3]],
  ['CHEM', 2022, CHEM_list[4]],
  ['CHEM', 2023, CHEM_list[5]],
  ['MATE', 2018, MATE_list[0]],
  ['MATE', 2019, MATE_list[1]],
  ['MATE', 2020, MATE_list[2]],
  ['MATE', 2021, MATE_list[3]],
  ['MATE', 2022, MATE_list[4]],
  ['MATE', 2023, MATE_list[5]],
  ['ENVI', 2018, ENVI_list[0]],
  ['ENVI', 2019, ENVI_list[1]],
  ['ENVI', 2020, ENVI_list[2]],
  ['ENVI', 2021, ENVI_list[3]],
  ['ENVI', 2022, ENVI_list[4]],
  ['ENVI', 2023, ENVI_list[5]],
  ['AGRI', 2018, AGRI_list[0]],
  ['AGRI', 2019, AGRI_list[1]],
  ['AGRI', 2020, AGRI_list[2]],
  ['AGRI', 2021, AGRI_list[3]],
  ['AGRI', 2022, AGRI_list[4]],
  ['AGRI', 2023, AGRI_list[5]],
  ['PHYS', 2018, PHYS_list[0]],
  ['PHYS', 2019, PHYS_list[1]],
  ['PHYS', 2020, PHYS_list[2]],
  ['PHYS', 2021, PHYS_list[3]],
  ['PHYS', 2022, PHYS_list[4]],
  ['PHYS', 2023, PHYS_list[5]],
  ['SOCI', 2018, SOCI_list[0]],
  ['SOCI', 2019, SOCI_list[1]],
  ['SOCI', 2020, SOCI_list[2]],
  ['SOCI', 2021, SOCI_list[3]],
  ['SOCI', 2022, SOCI_list[4]],
  ['SOCI', 2023, SOCI_list[5]],
  ['ENER', 2018, ENER_list[0]],
  ['ENER', 2019, ENER_list[1]],
  ['ENER', 2020, ENER_list[2]],
  ['ENER', 2021, ENER_list[3]],
  ['ENER', 2022, ENER_list[4]],
  ['ENER', 2023, ENER_list[5]],
]

export_data = pd.DataFrame(
  data,
  columns=['Subject_Area','Year','Count']
)

# Export merged data to csv
export_data.to_csv('merged_area_data.csv', index=False)